// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Medico from "./routes/Medico.tsx";
import * as $Paciente from "./routes/Paciente.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_Crear_otp from "./routes/api/Crear_otp.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $api_usuarios from "./routes/api/usuarios.ts";
import * as $index from "./routes/index.tsx";
import * as $sala_de_espera from "./routes/sala_de_espera.tsx";
import * as $Auth from "./islands/Auth.tsx";
import * as $Medico_1 from "./islands/Medico.tsx";
import * as $Paciente_1 from "./islands/Paciente.tsx";
import * as $Sala_de_espera from "./islands/Sala_de_espera.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Medico.tsx": $Medico,
    "./routes/Paciente.tsx": $Paciente,
    "./routes/_app.tsx": $_app,
    "./routes/api/Crear_otp.ts": $api_Crear_otp,
    "./routes/api/register.ts": $api_register,
    "./routes/api/usuarios.ts": $api_usuarios,
    "./routes/index.tsx": $index,
    "./routes/sala_de_espera.tsx": $sala_de_espera,
  },
  islands: {
    "./islands/Auth.tsx": $Auth,
    "./islands/Medico.tsx": $Medico_1,
    "./islands/Paciente.tsx": $Paciente_1,
    "./islands/Sala_de_espera.tsx": $Sala_de_espera,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
